# Use root/example as user/password credentials
version: '3.8'

services:
  db:
    container_name: mysql_local
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3307:3307
    expose:
      - 3307
    restart: always
    environment:
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=pass_local_user
      - MYSQL_PASSWORD=passlocal123
      - MYSQL_ROOT_PASSWORD=passlocal123
      - MYSQL_TCP_PORT=3307
      - TZ=Asia/Seoul
    command: >
      bash -c "chmod 044 /etc/mysql/conf.d/*.cnf && /entrypoint.sh mysqld"